// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrfnilirpvkukxqzgkbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyZm5pbGlycHZrdWt4cXpna2JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxODY3NzcsImV4cCI6MjA2OTc2Mjc3N30.SEusPf6YaEqAJvu_D35Crw2kI2hIqKMu3BZjhPV-JmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});